Single script run command
bitovi/jira-timeline-report pull request #110
Opened 2024-09-18 21:51 UTC by binaryberserker

use concurrently package to run tailwind watch, rollup watch, and start express locally

2024-09-18 22:24 UTC, binaryberserker commented on package.json
> +    "dev":"concurrently --kill-others --names \" CSS \",\" JS \",\" SERVER \" -c yellow,blue,green \"npm:fe:css:build\" \"npm:fe:js:build\" \"npm:start-local\"",
here's the magic line

2024-09-23 16:08 UTC, DavidNic11 commented
lgtm - there are some conflicts; can you resolve them?

2024-09-25 19:48 UTC, DavidNic11 commented on public/dist/hosted-main.min.js
Dist shouldn't be committed any more. Can you clear you dist cache and remove it from your pr

2024-09-25 19:48 UTC, DavidNic11 requested changes
rm dist from the pr

2024-09-26 22:10 UTC, DavidNic11 approved these changes

2024-09-26 22:11 UTC, merged